# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import statehouse_pb2 as statehouse_dot_v1_dot_statehouse__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in statehouse/v1/statehouse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatehouseServiceStub(object):
    """StatehouseService is the core gRPC service for Statehouse.
    All state operations go through this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Health',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.HealthRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Version = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Version',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.VersionRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/statehouse.v1.StatehouseService/BeginTransaction',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Write',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.WriteRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Delete',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.DeleteRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Commit',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.CommitRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/statehouse.v1.StatehouseService/Abort',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.AbortRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/statehouse.v1.StatehouseService/GetState',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.GetStateAtVersion = channel.unary_unary(
                '/statehouse.v1.StatehouseService/GetStateAtVersion',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionResponse.FromString,
                _registered_method=True)
        self.ListKeys = channel.unary_unary(
                '/statehouse.v1.StatehouseService/ListKeys',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.ScanPrefix = channel.unary_unary(
                '/statehouse.v1.StatehouseService/ScanPrefix',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixResponse.FromString,
                _registered_method=True)
        self.Replay = channel.unary_stream(
                '/statehouse.v1.StatehouseService/Replay',
                request_serializer=statehouse_dot_v1_dot_statehouse__pb2.ReplayRequest.SerializeToString,
                response_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ReplayEvent.FromString,
                _registered_method=True)


class StatehouseServiceServicer(object):
    """StatehouseService is the core gRPC service for Statehouse.
    All state operations go through this service.
    """

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Version information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Transaction lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Read operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateAtVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Replay (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatehouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.HealthRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.HealthResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.VersionRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.VersionResponse.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.WriteRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.DeleteRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.DeleteResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.CommitRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.CommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.AbortRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.AbortResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateResponse.SerializeToString,
            ),
            'GetStateAtVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateAtVersion,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionResponse.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ListKeysRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.ListKeysResponse.SerializeToString,
            ),
            'ScanPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPrefix,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixResponse.SerializeToString,
            ),
            'Replay': grpc.unary_stream_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=statehouse_dot_v1_dot_statehouse__pb2.ReplayRequest.FromString,
                    response_serializer=statehouse_dot_v1_dot_statehouse__pb2.ReplayEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statehouse.v1.StatehouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statehouse.v1.StatehouseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatehouseService(object):
    """StatehouseService is the core gRPC service for Statehouse.
    All state operations go through this service.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Health',
            statehouse_dot_v1_dot_statehouse__pb2.HealthRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Version',
            statehouse_dot_v1_dot_statehouse__pb2.VersionRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/BeginTransaction',
            statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.BeginTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Write',
            statehouse_dot_v1_dot_statehouse__pb2.WriteRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Delete',
            statehouse_dot_v1_dot_statehouse__pb2.DeleteRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Commit',
            statehouse_dot_v1_dot_statehouse__pb2.CommitRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/Abort',
            statehouse_dot_v1_dot_statehouse__pb2.AbortRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/GetState',
            statehouse_dot_v1_dot_statehouse__pb2.GetStateRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateAtVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/GetStateAtVersion',
            statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.GetStateAtVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/ListKeys',
            statehouse_dot_v1_dot_statehouse__pb2.ListKeysRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statehouse.v1.StatehouseService/ScanPrefix',
            statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.ScanPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/statehouse.v1.StatehouseService/Replay',
            statehouse_dot_v1_dot_statehouse__pb2.ReplayRequest.SerializeToString,
            statehouse_dot_v1_dot_statehouse__pb2.ReplayEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
